import {
  FaHouse,
  FaUser,
  FaGear,
  FaRegHeart,
  FaHeart,
  FaGithub,
  FaMagnifyingGlass,
  FaBagShopping,
  FaBars,
  FaXmark,
  FaInstagram,
  FaWhatsapp,
  FaChevronLeft,
  FaChevronRight,
  FaLock,
  FaEnvelope,
  FaPhone,
  FaRegClock,
  FaLocationDot,
  FaCompass,
  FaSwatchbook,
  FaPencil,
  FaCalendarCheck,
  FaFileArrowUp,
} from "react-icons/fa6";
import type {IconComponent} from "./icon";

export const ICONS = {
  home: FaHouse,
  user: FaUser,
  settings: FaGear,
  heartOutline: FaRegHeart,
  heart: FaHeart,
  github: FaGithub,
  search: FaMagnifyingGlass,
  cart: FaBagShopping,
  menu: FaBars,
  close: FaXmark,
  instagram: FaInstagram,
  whatsapp: FaWhatsapp,
  chevronLeft: FaChevronLeft,
  chevronRight: FaChevronRight,
  lock: FaLock,
  envelope: FaEnvelope,
  phone: FaPhone,
  clock: FaRegClock,
  mapPin: FaLocationDot,
  compass: FaCompass,
  swatchbook: FaSwatchbook,
  pencil: FaPencil,
  calendarCheck: FaCalendarCheck,
  fileUpload: FaFileArrowUp,
} as const satisfies Record<string, IconComponent>;

export type IconName = keyof typeof ICONS;
